USE RetailSalesDB;
GO

/*==========================================================
                    EXECUTIVE KPI ANALYSIS
==========================================================*/


/*----------------------------------------------------------
Business Question:
What is the total revenue generated by the business?

Business Value:
Provides an overall view of company sales performance and
serves as the primary KPI for executive reporting.
-----------------------------------------------------------*/

SELECT
    SUM(Sales) AS TotalRevenue
FROM FactSales;



/*----------------------------------------------------------
Business Question:
What is the total profit earned by the company?

Business Value:
Measures overall profitability and helps management evaluate
financial performance.
-----------------------------------------------------------*/

SELECT
    SUM(Profit) AS TotalProfit
FROM FactSales;



/*----------------------------------------------------------
Business Question:
How many unique customer orders were placed?

Business Value:
Indicates customer demand and overall business activity.
-----------------------------------------------------------*/

SELECT
    COUNT(DISTINCT OrderID) AS TotalOrders
FROM FactSales;



/*----------------------------------------------------------
Business Question:
How many products were sold?

Business Value:
Measures total sales volume.
-----------------------------------------------------------*/

SELECT
    SUM(Quantity) AS TotalQuantitySold
FROM FactSales;



/*----------------------------------------------------------
Business Question:
What is the Average Order Value (AOV)?

Business Value:
Shows how much customers spend per order on average.
Useful for pricing and marketing strategies.
-----------------------------------------------------------*/

SELECT

ROUND(

SUM(Sales) /
COUNT(DISTINCT OrderID)

,2)

AS AverageOrderValue

FROM FactSales;



/*----------------------------------------------------------
Business Question:
What is the overall Profit Margin?

Business Value:
Measures how efficiently revenue is converted into profit.
-----------------------------------------------------------*/

SELECT

ROUND(

SUM(Profit)*100.0/SUM(Sales)

,2)

AS ProfitMarginPercentage

FROM FactSales;

/*==========================================================
                REVENUE TREND ANALYSIS
==========================================================*/


/*----------------------------------------------------------
Business Question:
How has revenue changed over the years?

Business Value:
Identifies long-term business growth trends and supports
strategic planning.
-----------------------------------------------------------*/

SELECT

D.Year,

SUM(F.Sales) AS Revenue

FROM FactSales F

JOIN DimDate D

ON F.DateKey=D.DateKey

GROUP BY D.Year

ORDER BY D.Year;



/*----------------------------------------------------------
Business Question:
What is the monthly revenue trend?

Business Value:
Helps identify seasonal demand patterns and monthly sales
performance.
-----------------------------------------------------------*/

SELECT

D.Year,

D.Month,

D.MonthName,

SUM(F.Sales) AS Revenue

FROM FactSales F

JOIN DimDate D

ON F.DateKey=D.DateKey

GROUP BY

D.Year,

D.Month,

D.MonthName

ORDER BY

D.Year,

D.Month;

/*==========================================================
                REGIONAL PERFORMANCE
==========================================================*/


/*----------------------------------------------------------
Business Question:
Which regions generate the highest revenue and profit?

Business Value:
Helps management identify high-performing and low-performing
markets for future investments.
-----------------------------------------------------------*/

SELECT

G.Region,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit

FROM FactSales F

JOIN DimGeography G

ON F.GeographyKey=G.GeographyKey

GROUP BY G.Region

ORDER BY Revenue DESC;



/*----------------------------------------------------------
Business Question:
Which states contribute the highest revenue?

Business Value:
Supports regional expansion and sales planning.
-----------------------------------------------------------*/

SELECT

G.State,

SUM(F.Sales) AS Revenue

FROM FactSales F

JOIN DimGeography G

ON F.GeographyKey=G.GeographyKey

GROUP BY G.State

ORDER BY Revenue DESC;

/*==========================================================
                CUSTOMER ANALYTICS
==========================================================*/


/*----------------------------------------------------------
Business Question:
Who are the top 10 customers by revenue?

Business Value:
Identifies high-value customers for loyalty programs,
personalized marketing, and retention strategies.
-----------------------------------------------------------*/

SELECT TOP 10

C.Customer_Name,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit

FROM FactSales F

JOIN DimCustomer C
ON F.CustomerKey = C.CustomerKey

GROUP BY C.Customer_Name

ORDER BY Revenue DESC;



/*----------------------------------------------------------
Business Question:
Which customer segment generates the highest revenue?

Business Value:
Helps understand which customer segment contributes most
to business growth.
-----------------------------------------------------------*/

SELECT

C.Segment,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit,

COUNT(DISTINCT F.OrderID) AS Orders

FROM FactSales F

JOIN DimCustomer C
ON F.CustomerKey = C.CustomerKey

GROUP BY C.Segment

ORDER BY Revenue DESC;



/*----------------------------------------------------------
Business Question:
What is the average revenue generated per customer?

Business Value:
Measures customer value and supports customer acquisition
and retention strategies.
-----------------------------------------------------------*/

SELECT

ROUND(

SUM(Sales) * 1.0 /
COUNT(DISTINCT CustomerKey)

,2)

AS AverageRevenuePerCustomer

FROM FactSales;

/*==========================================================
                PRODUCT ANALYTICS
==========================================================*/


/*----------------------------------------------------------
Business Question:
Which are the top 10 products by revenue?

Business Value:
Identifies best-selling products to optimize inventory,
marketing, and promotions.
-----------------------------------------------------------*/

SELECT TOP 10

P.Product_Name,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit

FROM FactSales F

JOIN DimProduct P
ON F.ProductKey = P.ProductKey

GROUP BY P.Product_Name

ORDER BY Revenue DESC;



/*----------------------------------------------------------
Business Question:
Which are the bottom 10 products by revenue?

Business Value:
Highlights underperforming products for business review.
-----------------------------------------------------------*/

SELECT TOP 10

P.Product_Name,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit

FROM FactSales F

JOIN DimProduct P
ON F.ProductKey = P.ProductKey

GROUP BY P.Product_Name

ORDER BY Revenue ASC;



/*----------------------------------------------------------
Business Question:
Which product categories generate the highest revenue?

Business Value:
Supports strategic investment in high-performing categories.
-----------------------------------------------------------*/

SELECT

P.Category,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit

FROM FactSales F

JOIN DimProduct P
ON F.ProductKey = P.ProductKey

GROUP BY P.Category

ORDER BY Revenue DESC;



/*----------------------------------------------------------
Business Question:
How do sub-categories perform?

Business Value:
Identifies strong and weak product lines.
-----------------------------------------------------------*/

SELECT

P.Sub_Category,

SUM(F.Sales) AS Revenue,

SUM(F.Profit) AS Profit

FROM FactSales F

JOIN DimProduct P
ON F.ProductKey = P.ProductKey

GROUP BY P.Sub_Category

ORDER BY Revenue DESC;


/*==========================================================
                PROFITABILITY ANALYSIS
==========================================================*/


/*----------------------------------------------------------
Business Question:
Which products are generating losses?

Business Value:
Helps management identify products requiring pricing,
discount, or inventory review.
-----------------------------------------------------------*/

SELECT TOP 20

P.Product_Name,

SUM(F.Profit) AS TotalLoss

FROM FactSales F

JOIN DimProduct P
ON F.ProductKey = P.ProductKey

GROUP BY P.Product_Name

HAVING SUM(F.Profit) < 0

ORDER BY TotalLoss;



/*----------------------------------------------------------
Business Question:
How does discount affect profit?

Business Value:
Evaluates whether high discounts reduce profitability.
-----------------------------------------------------------*/

SELECT

Discount,

SUM(Sales) AS Revenue,

SUM(Profit) AS Profit

FROM FactSales

GROUP BY Discount

ORDER BY Discount;



/*----------------------------------------------------------
Business Question:
Which categories are most profitable?

Business Value:
Supports strategic planning and resource allocation.
-----------------------------------------------------------*/

SELECT

P.Category,

ROUND(
SUM(F.Profit)*100.0/SUM(F.Sales),2
) AS ProfitMargin

FROM FactSales F

JOIN DimProduct P
ON F.ProductKey = P.ProductKey

GROUP BY P.Category

ORDER BY ProfitMargin DESC;

/*==========================================================
                SHIPPING ANALYSIS
==========================================================*/


/*----------------------------------------------------------
Business Question:
Which shipping mode generates the highest revenue?

Business Value:
Evaluates customer shipping preferences and operational
performance.
-----------------------------------------------------------*/

SELECT

ShipMode,

SUM(Sales) AS Revenue,

SUM(Profit) AS Profit,

COUNT(OrderID) AS Orders

FROM FactSales

GROUP BY ShipMode

ORDER BY Revenue DESC;